image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      flutter doctor
      flutter pub get
    command: flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

ports:
  - port: 8080
    onOpen: open-preview
