image:
  file: Dockerfile

tasks:
  - name: Flutter vorbereiten
    init: |
      flutter pub get
    command: |
      echo "Flutter-Umgebung bereit!"

ports:
  - port: 3000
    onOpen: open-preview
    description: Flutter Web Preview

vscode:
  extensions:
    - Dart-Code.flutter
