image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      flutter config --android-sdk /usr/lib/android-sdk
      flutter doctor
      flutter config --enable-web
    command: flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

ports:
  - port: 8080
    onOpen: open-preview
